# NumPy
* NumPy es un paquete de Python que significa “Numerical Python”, es la librería principal para la informática científica, proporciona potentes estructuras de datos, implementando matrices y matrices multidimensionales. Estas estructuras de datos garantizan cálculos eficientes con matrices.

*Los arreglos son estructuras de datos estáticas, ya que hay que declarar su tamaño antes de utilizarlos. A diferencia de los arreglos, las listas son estructuras de datos que pueden ir creciendo conforme se vaya requiriendo, por eso se considera que es una estructura de datos dinámica.* [Fuente](http://132.248.48.64/repositorio/moodle/pluginfile.php/1469/mod_resource/content/1/contenido/index.html)

In [1]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8]  # crear una lista

In [3]:
x1 = np.array(L1)    # creación de arrays
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype = "float32")
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_ , intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-9999999999e99999)
- complex_ , complex64, complex128 (a +bi, a, b $\in$ float_)

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,12, dtype = np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
np.arange(4,5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [35]:
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
x = np.zeros((8,3))

In [15]:
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.ravel(x) # aquí queremos aplanar el array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.transpose(x) # trasponer

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [21]:
np.resize(x,(5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios

  1. Crear un Array de datos con valores entre 5 y 120.
  2. Crear una matriz de 4x4 con los valores desde 0 hasta 15.
  3. Crear la identidad 7x7.
  4. Crear un array de 20 elementos y transformarlos en una matriz 5x4.
  5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme.  

In [25]:
# Array de datos con valores entre 5 y 120.
ar1 = np.arange(5,121)
ar1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [27]:
# Crear una matriz de 4x4 con los valores desde 0 hasta 15.

ar2 = np.arange(16)
ar2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
#Crear la identidad 7x7.
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [43]:
# Crear un array de 20 elementos y transformarlos en una matriz 5x4.
ar3 = np.arange(1, 21, 1)

ar3.reshape(5,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [44]:
# Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme.
np.linspace(0,5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedades de los arrays

In [45]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
x.ndim # consulta la dimensión del array

2

In [47]:
x.shape # consulta el orden filas columnas

(3, 4)

In [48]:
x.size # tamaños de la matriz

12

In [49]:
x.dtype # indica el tipo de dato

dtype('int32')

In [50]:
x.itemsize # tamaño en memoria de la matriz

4

In [51]:
x.data

In [52]:
x[2] # fila numero dos

array([ 8,  9, 10, 11])

In [53]:
x[2,1] # fila dos columnas 1

9

In [54]:
x.shape = (4,3) # es una especie de reshape
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [56]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
y[3:8]

array([3, 4, 5, 6, 7])

In [58]:
y[1:7:2]

array([1, 3, 5])

In [59]:
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [60]:
y[z]

array([10,  9,  8,  7])

In [62]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [63]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [65]:
cond = (x<25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [66]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
x[12:24] = 1

In [68]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
x[13:16] = [6,9,12]

In [70]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
x.dtype

dtype('int32')

In [72]:
x[5]=3.1414

In [73]:
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de arrays

In [74]:
x = np.arange(10)

In [75]:
y = x

In [76]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
y.shape =(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
z is x

False

In [81]:
x is y

True

In [82]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
t.shape = (5,2)

In [84]:
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [85]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

* Mantener en mente la diferencia entre las asignaciones, copias y vistas. 

## Funciones universales (ufunc)

- unarias:sqrt, sin, cos, **2
- Binarias: Maximum, Minimum


In [86]:
x = np.arange(10)

In [87]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
x - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [90]:
x * 3 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [91]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [92]:
alpha = np.linspace(0, 2*np.pi, 4)

In [93]:
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [95]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [96]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [97]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [98]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [99]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [100]:
np.power(x,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [101]:
np.log2(x)

<ipython-input-101-55ee5869f62c>:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

$$\sum_{i=1}^n x_i$$

In [102]:
np.sum(x)

45

In [103]:
np.nansum(x)

45

In [104]:
np.prod(x)

0

In [105]:
np.mean(x)

4.5

In [106]:
np.median(x)

4.5

In [107]:
np.min(x)

0

In [108]:
np.max(x)

9

In [109]:
np.std(x)

2.8722813232690143

In [110]:
np.var(x)

8.25

In [112]:
np.argmin(x)

0

In [113]:
np.argmax(x)

9

In [117]:
np.percentile(x, q = 50)

4.5

In [116]:
np.any(x)

True

In [118]:
np.all(x)

False

In [127]:
np.random.seed(2019)
z = np.random.random((3,5))
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [128]:
z.sum()

8.550690063213514

In [126]:
z.sum(axis = 0)

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [123]:
z.sum(axis = 1)

array([2.63192144, 2.99936276, 2.10657353])